invalidItems: [PORKCHOP,POTATO,CHICKEN,BEEF,RABBIT,MUTTON,COD,SALMON,KELP,DIAMOND_SHOVEL,WOODEN_SHOVEL,STONE_SHOVEL,
               IRON_SHOVEL,NETHERITE_SHOVEL,FLINT_AND_STEEL]
restPercent: 75.0
skipDayWhileResting: true